- name: Install Apache on Web server
  hosts: 
    - web1
    - web2
  tasks:
    - name: Start apache server on webservers (from github) and git (and making changes in gfeature 1)
      service: 
        name: apache2
        state: started
        enabled: yes
      become: true
