- name: Uninstall Apache on Web server
  hosts: 
    - web1
    - web2
    - loadbalancer
  vars:
    apps:
      - apache2
      - php
  tasks:

    - name: Uninstall Apache server from all systems and machines (checking the change) test
      apt:
        name: "{{ apps }}"
        state: absent
      become: true
